#!/bin/bash
if [ -f ".gitignore" ]; then
  if [ -f ".srclist" ]; then
    ctags -R --exclude='.git' --exclude='tmp' --exclude='node_modules' --exclude='bower_components' --exclude='dist' -L .srclist
  else
    ctags -R --exclude='.git' --exclude='tmp' --exclude='node_modules' --exclude='bower_components' --exclude='dist' .
  fi
else
  HERE=$PWD
  cd ..
  if [ "$PWD" = "$HERE" ]; then
    echo "Got to /, have not found your project root, abort!"
    exit 1
  fi
  exec "$0"
fi
# EOF
